name: Label Predicate Changes

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Label PR if predicates changed
      uses: actions/github-script@v6
      with:
        script: |
          const keywords = ['predicate', 'biolink:'];  // Define keywords
          const labelName = 'Biological Context QC';  // Label to apply
          
          // Determine if the event is for an issue or pull request
          const isIssue = context.event.issue !== undefined;
          const number = isIssue ? context.event.issue.number : context.event.pull_request.number;
          const item = isIssue ? context.issue : context.payload.pull_request;
          
          // Check if the title or body contains any keywords
          const containsKeyword = (text) => {
            return keywords.some(keyword => text.toLowerCase().includes(keyword.toLowerCase()));
          };
          
          if (containsKeyword(item.title) || containsKeyword(item.body)) {
            // Add label if keywords found
            await github.issues.addLabels({
              ...context.repo,
              issue_number: number,
              labels: [labelName]
            });
          }

    - name: Assign Issue if Labeled
      uses: actions/github-script@v6
      if: github.event.action == 'labeled' && github.event.label.name == 'Biological Context QC'
      with:
        script: |
          const assignee = 'eKathleenCarter';  // Change this to the desired assignee's GitHub username
          
          // Assign the issue
          await github.issues.addAssignees({
            ...context.repo,
            issue_number: context.issue.number,
            assignees: [assignee]
          });